# Masukkan daftar pertanyaan disini

list_pertanyaan = [
    'Siapa panggilan masa kecil anda?',
    'Kecelakaan apa yang paling parah anda alami?',
    'Apa pengalaman paling awal yang anda ingat?',
    'Nama sekolah pertama yang anda masuki?',
    'Apa nama film kartun kesukaanmu ketika kecil?',
    'Pada kelas berapa kamu pertama kali punya HP?',
    'Kapan terakhir kali anda terlibat dalam perkelahian?',
    'Kapan terakhir kali anda menangis?',
    'Apa tempat favorit anda untuk jalan-jalan?',
    'Apa nama negara paling pengen anda kunjungi?',
    'Siapa nama sahabat anda di masa kecil?',
    'Siapa nama binatang peliharaan favorit anda?',
    'Apa kelemahan terbesarmu?',
    'Apa panggilan untuk kakekmu?',
    'Tokoh yang paling menginspirasi bagi anda?',
    'Apa kenangan favorit masa kecil anda?',
    'Apa nasehat yang akan anda berikan kepada diri anda 10 tahun yang lalu?',
    'Apa kejadian paling menakutkan yang pernah anda alami?',
    'Apa konten youtube yang paling anda sukai?',
    'Jika anda punya uang 10M dan harus dibelanjakan, apa yang akan kamu beli?'
    'Apa pelajaran yang paling anda sukai ketika SD?',
    'Apa pelajaran yang paling anda benci ketika SD?',
    'Apa kota yang paling anda pengen kunjungi di Indonesia?',
    'Jika kamu mendapatkan gelar PhD di suatu bidang ilmu, apa bidang itu?',
    'Buah-buahan apa yang paling kamu sukai?',
    'Buah-buahan apa yang paling TIDAK kamu suka?',
    'Apa panggilan untuk ayahmu ketika kamu kecil?',
    'Apa sayuran yang paling kamu suka?',
    'Apa sayuran yang paling TIDAK kamu suka?',
    'Kalau di masa depan kamu punya bisnis yang sukses, di bidang apakah bisnis tersebut?',
    'Apa makanan khas Indonesia favoritmu?',
    'Apa rasa es krim favoritmu?',
    'Apa kenangan masa SD yang paling anda sukai?',
    'Jika anda dapat memilih untuk menguasai suatu softskill, apakah itu?',
    'Apa kombinasi dua buah yang di-mix untuk dijadikan jus?',
    'Apa olahraga favoritmu?',
    'Apa nama perusahaan top dunia yang anda ingin bekerja padanya?',
    'Apa film bioskop kesukaan anda?',
    'Kalau anda punya rumah makan, kira-kira mau dinamakan apa?',
    'Apa tokoh kartun favoritmu?',
    'Apa nama game komputer/console yang pertama kamu mainkan?',
    'Apa salah satu makanan masa kecil yang kamu rindukan sekarang?',
    'Apa ketakutan terbesarmu?',
    'Siapa nama guru favoritmu semasa kecil?',
    'Apa bakat atau kemampuan unik yang kamu miliki?',
    'Apa mimpi paling aneh yang kamu alami?',
    'Kalau kamu boleh memiliki tato, apakah gambar tato tersebut?',
    'Kalau kamu boleh memiliki tato, di bagian tubuh manakah tato tersebut ingin kamu letakkan?',
    'Siapa nama orang pertama yang kamu kenal di perkuliahan?',
    'Siapa nama dosen favoritmu selama masa perkuliahan?',
    'Apa nama film anime yang paling kamu sukai?',
    'Apa mata kuliah favoritmu selama kuliah?',
    'Tiga kata apa yang mewakili pasangan idamanmu?',
    'Apa acara TV favoritmu?',
    'Teori konspirasi apa yang paling kamu percayai?'
]


