# Masukkan daftar pertanyaan disini

list_pertanyaan = [
    'Siapa panggilan masa kecilmu?',
    'Kecelakaan apa yang paling parah kamu alami?',
    'Apa pengalaman paling awal yang kamu ingat?',
    'Nama sekolah pertama yang kamu masuki?',
    'Apa nama film kartun kesukaanmu ketika kecil?',
    'Pada kelas berapa kamu pertama kali punya HP?',
    'Kapan terakhir kali kamu terlibat dalam perkelahian?',
    'Kapan terakhir kali kamu menangis?',
    'Apa tempat favorit kamu untuk jalan-jalan?',
    'Apa nama negara paling pengen kamu kunjungi?',
    'Siapa nama sahabat kamu di masa kecil?',
    'Siapa nama binatang peliharaan favorit kamu?',
    'Apa kelemahan terbesarmu?',
    'Apa panggilan untuk kakekmu?',
    'Apa panggilan untuk nenekmu?',
    'Tokoh yang paling menginspirasi bagi kamu?',
    'Apa kenangan favorit masa kecil kamu?',
    'Apa nasehat yang akan kamu berikan kepada diri kamu 10 tahun yang lalu?',
    'Apa kejadian paling menakutkan yang pernah kamu alami?',
    'Apa konten youtube yang paling kamu sukai?',
    'Jika kamu punya uang 10M dan harus dibelanjakan, apa yang akan kamu beli?',
    'Apa pelajaran yang paling kamu sukai ketika SD?',
    'Apa pelajaran yang paling kamu benci ketika SD?',
    'Apa kota yang paling kamu pengen kunjungi di Indonesia?',
    'Jika kamu mendapatkan gelar PhD di suatu bidang ilmu, apa bidang itu?',
    'Buah-buahan apa yang paling kamu sukai?',
    'Buah-buahan apa yang paling TIDAK kamu suka?',
    'Apa panggilan untuk ayahmu ketika kamu kecil?',
    'Apa panggilan untuk ibumu ketika kamu kecil?',
    'Apa sayuran yang paling kamu suka?',
    'Apa sayuran yang paling TIDAK kamu suka?',
    'Kalau di masa depan kamu punya bisnis yang sukses, di bidang apakah bisnis tersebut?',
    'Apa makanan khas Indonesia favoritmu?',
    'Apa rasa es krim favoritmu?',
    'Apa kenangan masa SD yang paling kamu sukai?',
    'Jika kamu dapat memilih untuk menguasai suatu softskill, apakah itu?',
    'Apa kombinasi dua buah yang di-mix untuk dijadikan jus?',
    'Apa olahraga favoritmu?',
    'Apa nama perusahaan top dunia yang kamu ingin bekerja padanya?',
    'Apa film bioskop kesukaan kamu?',
    'Kalau kamu punya rumah makan, kira-kira mau dinamakan apa?',
    'Apa tokoh kartun favoritmu?',
    'Apa nama game komputer/console yang pertama kamu mainkan?',
    'Apa salah satu makanan masa kecil yang kamu rindukan sekarang?',
    'Apa ketakutan terbesarmu?',
    'Siapa nama guru favoritmu semasa kecil?',
    'Apa bakat atau kemampuan unik yang kamu miliki?',
    'Apa mimpi paling aneh yang kamu alami?',
    'Kalau kamu boleh memiliki tato, apakah gambar tato tersebut?',
    'Kalau kamu boleh memiliki tato, di bagian tubuh manakah tato tersebut ingin kamu letakkan?',
    'Siapa nama orang pertama yang kamu kenal di perkuliahan?',
    'Siapa nama dosen favoritmu selama masa perkuliahan?',
    'Apa nama film anime yang paling kamu sukai?',
    'Apa mata kuliah favoritmu selama kuliah?',
    'Apa mata kuliah yang paling TIDAK kamu suka selama kuliah?',
    'Tiga kata apa yang mewakili pasangan idamanmu?',
    'Apa acara TV favoritmu?',
    'Teori konspirasi apa yang paling kamu percayai?',
    'Film apa yang pertama kali tonton di bioskop?',
    'Jika kamu disuruh menyanyikan sebuah lagu di karaoke, lagu apakah itu?',
    'Apa film disney kesukaanmu?',
    'Apa hal paling berani yang pernah kamu lakukan?',
    'Apa acara paling seru yang kamu hadiri yang paling berkesan pada masa kecilmu?',
    'Apa hadiah ulang tahunmu yang paling berkesan?',
    'Siapa ilmuwan terkenal yang paling kamu kagumi?',
    'Siapa nama selebriti yang paling kamu kagumi?',
    'Siapa nama atlit olahraga yang paling kamu kagumi?',
    'Siapa pahlawan superhero favoritmu?',
    'Jika kamu mampu memiliki suatu perusahaan top dunia, perusahaan apakah itu?',
    'Apa cemilan yang paling kamu sukai untuk dimakan di malam hari?',
    'Apa nama pokemon yang ingin kamu pelihara?',
    'Berapa jumlah mantan yang kamu miliki?',
    'Apa makanan yang tidak bosan-bosan nya kamu makan?',
    'Apa makanan yang pernah kamu coba tapi tidak akan mau mencobanya kembali?',
    'Apa benda yang kamu pernah beli yang paling kamu sesali?',
    'Apa salah satu film yang tidak bosan kamu tonton berulang kali',
    'Apa grup band favoritmu?',
    'Siapa penyanyi favoritmu?',
    'Siapa penyanyi yang menurutmu overrated?',
    'Apa film yang menurutmu overrated?',
    'Siapa atlit yang menurutmu overrated?',
    'Berapa total sepupumu dari ayahmu?',
    'Berapa total sepupumu dari ibumu?',
    'Apa merek shampo mu?',
    'Apa minuman yang paling mahal yang pernah kamu beli?',
    'Apa hal yang kamu suka tapi orang pada umumnya tidak?',
    'Jika kamu dapat menguasai satu alat musik, alat musik apakah itu?',
    'Jika suaramu bisa berubah, siapa orang yang kamu ingin suaramu berubah jadi?',
    'Apa media sosial pertama yang gunakan?',
    'Apa media sosial yang terakhir kamu gunakan? (Selain discord dong)',
    'Jika kamu dapat terkenal di salah satu media sosial, media sosial apakah itu?',
    'Jika kamu menjadi terkenal, kamu ingin terkenal karena apa?',
    'Siapa penyanyi yang menurutmu underrated?',
    'Apa film yang menurutmu underrated?',
    'Siapa atlit yang menurutmu underrated?',
    'Apa nickname game online pertamamu?',
    'Bahasa apa yang paling ingin kamu kuasai?',
    'Bahasa yang paling sulit apa yang pernah kamu coba pelajari?',
    'Makanan apa yang paling sulit yang kamu pernah masak?',
    'Kalau kamu diberi kekuatan super, kekuatan super apa itu?',
    'Apa minuman favoritmu?',
    'Apa makanan favoritmu?',
    'Apa merek mobil idamanmu?',
    'Makhlus mitos apa yang pengen kamu pelihara?',
    'Apa makanan yang paling mahal yang pernah kamu beli?',
    'Apa makanan seafood favoritmu?',
    'Apa barang pertama yang kamu beli secara online?',
    'Apa barang terakhir yang kamu beli secara online?',
    'Apa tokoh kartun yang menurutmu paling lucu?',
    'Apa hobi kamu yang kebanyakan orang tidak tau?',
    'Apa cita-cita kamu ketika masih kecil?',
    'Apa hadiah paling berkesan yang pernah kamu dapatkan?',
    'Jika kamu bisa memelihara binatang apa saja, binatang apakah itu?',
    'Jika kamu dapat membangun rumah impianmu, apa hal wajib yang harus rumah itu punya?',
    'Apa jajanan favoritmu ketika kecil?',
    'Apa jenis gorengan favoritmu?',
    'Apa rasa indomie favoritmu?',
    'Apa merek sabun badanmu?',
    'Apa kesamaan kamu yang paling dekat dengan ayahmu?',
    'Apa kesamaan kamu yang paling dekat dengan ibumu?',
    'Siapa nama teman tetanggamu dulu ketika kecil?',
    'Siapa penyanyi pria Indonesia yang menurutmu memiliki suara yang paling bagus?',
    'Siapa penyanyi wanita Indonesia yang menurutmu memiliki suara yang paling bagus?',
    'Berapa kali kamu pernah pindah rumah?',
    'Jika kamu memiliki sebuah lukisan yang terjual mahal, gambar apakah di lukisan itu?',
    'Jika kamu dapat menjadi seorang atlit olahraga, olahraga apakah itu?',
    'Film apa yang belum pernah kamu tonton, tapi tertarik untuk menontonnya?',
    'Di film naruto, jika kamu dapat memiliki kekuatan dari salah satu tokoh di film tersebut, siapakah itu?',
    'Apa pendapatmu tentang presiden Joko Widodo?',
    'Apa hal baru yang kamu pelajari belakangan ini?',
    'Kapan terakhir kamu menangis?',
    'Apa fakta dirimu yang kebanyakan orang tidak tau?',
    'Apa binatang yang paling kamu benci?',
    'Siapa orang yang paling pantas menurut anda untuk maju jadi presiden untuk periode yang akan datang?',
    'Ada daya tarik utama anda?',
    'Jika anda bisa bertukar kehidupan dengan salah satu orang disini, siapa yg akan anda pilih?',
    'Apa hal yang sering anda pikirkan saat sedang duduk di toilet?',
    'Apa hal yang paling anda tidak sukai pada diri anda sendiri?',
    'Berapa harikah lamanya anda pernah tidak mandi?',
    'Hal apa yang pernah anda lihat yang paling membuat anda mual?',
    'Jika anda hanya bisa mendengarkan satu lagu seumur hidup anda, lagu apa yg akan anda pilih?',
    'Jika anda bisa melupakan satu kenangan dikehidupan anda, kenangan apakah itu?',
    'Hal apa yang membuat anda terakhir kali menangis?',
    'Hal apa yang membuat anda terakhir kali ketawa terbahak-bahak?',
    'Jika anda bisa merubah nama anda, nama apakah yang anda inginkan?',
    'Hal apakah yang pernah anda lakukan untuk terlihat lebih "cool" didepan orang lain?',
    'Bagian tubuh apakah yang paling anda banggakan?',
    'Jika anda bisa menikah dengan salah satu karakter anime, siapa yang anda ingin nikahi?',
    'Jika anda bisa merubah gender selama satu hari, hal apa yang anda ingin lakukan?',
    'Siapakah orang di server ini yang memiliki sifat terbaik menurut anda? Dan apa alasannya?',
    'Sifat apakah yang anda cari dari pasangan anda?',
    'Berapa umur target anda menikah?',
    'Apa hal/sifat dari lawan jenis yang menjadi deal breaker bagimu?',
    'Apa target yang kamu punya untuk waktu yang akan datang?',
    'Apa hal/sifat dari dirimu yang kebanyakan orang tidak mengetahuinya?',
    'Jika presiden Jokowi muncul dalam mimpimu, apa kata-kata yang sedang dia ucapkan?',
    'Siapa artis / public figure yang merupakan tipe idaman untuk menjadi pasanganmu?',
    'Apa hal aneh yang kamu percaya tapi kebanyakan orang tidak?',
    'Apa artis hollywood yang berlawan jenis dengan anda yang memiliki ciri fisik idaman anda?',
    'Apa hal baru dari kehidupan yang anda pelajari satu tahun belakangan?',
    'Apa hal yang ingin anda rubah / ingin lakukan jika diberi kesempatan kembali ke masa SMA anda?',
    'Apa video terakhir yang anda tonton di youtube?',
    'Apa makanan yang menurutmu underrated?'
]

list_pertanyaan_2 = [
    ['Jika ', ' muncul di mimpimu, apa yang sedang dia lakukan?'],
    ['']
]
