# Masukkan daftar pertanyaan disini

list_pertanyaan = [
    'Siapa panggilan masa kecilmu?',
    'Kecelakaan apa yang paling parah kamu alami?',
    'Apa pengalaman paling awal yang kamu ingat?',
    'Nama sekolah pertama yang kamu masuki?',
    'Apa nama film kartun kesukaanmu ketika kecil?',
    'Pada kelas berapa kamu pertama kali punya HP?',
    'Kapan terakhir kali kamu terlibat dalam perkelahian?',
    'Kapan terakhir kali kamu menangis?',
    'Apa tempat favorit kamu untuk jalan-jalan?',
    'Apa nama negara paling pengen kamu kunjungi?',
    'Siapa nama sahabat kamu di masa kecil?',
    'Siapa nama binatang peliharaan favorit kamu?',
    'Apa kelemahan terbesarmu?',
    'Apa panggilan untuk kakekmu?',
    'Apa panggilan untuk nenekmu?',
    'Tokoh yang paling menginspirasi bagi kamu?',
    'Apa kenangan favorit masa kecil kamu?',
    'Apa nasehat yang akan kamu berikan kepada diri kamu 10 tahun yang lalu?',
    'Apa kejadian paling menakutkan yang pernah kamu alami?',
    'Apa konten youtube yang paling kamu sukai?',
    'Jika kamu punya uang 10M dan harus dibelanjakan, apa yang akan kamu beli?',
    'Apa pelajaran yang paling kamu sukai ketika SD?',
    'Apa pelajaran yang paling kamu benci ketika SD?',
    'Apa kota yang paling kamu pengen kunjungi di Indonesia?',
    'Jika kamu mendapatkan gelar PhD di suatu bidang ilmu, apa bidang itu?',
    'Buah-buahan apa yang paling kamu sukai?',
    'Buah-buahan apa yang paling TIDAK kamu suka?',
    'Apa panggilan untuk ayahmu ketika kamu kecil?',
    'Apa panggilan untuk ibumu ketika kamu kecil?',
    'Apa sayuran yang paling kamu suka?',
    'Apa sayuran yang paling TIDAK kamu suka?',
    'Kalau di masa depan kamu punya bisnis yang sukses, di bidang apakah bisnis tersebut?',
    'Apa makanan khas Indonesia favoritmu?',
    'Apa rasa es krim favoritmu?',
    'Apa kenangan masa SD yang paling kamu sukai?',
    'Jika kamu dapat memilih untuk menguasai suatu softskill, apakah itu?',
    'Apa kombinasi dua buah yang di-mix untuk dijadikan jus?',
    'Apa olahraga favoritmu?',
    'Apa nama perusahaan top dunia yang kamu ingin bekerja padanya?',
    'Apa film bioskop kesukaan kamu?',
    'Kalau kamu punya rumah makan, kira-kira mau dinamakan apa?',
    'Apa tokoh kartun favoritmu?',
    'Apa nama game komputer/console yang pertama kamu mainkan?',
    'Apa salah satu makanan masa kecil yang kamu rindukan sekarang?',
    'Apa ketakutan terbesarmu?',
    'Siapa nama guru favoritmu semasa kecil?',
    'Apa bakat atau kemampuan unik yang kamu miliki?',
    'Apa mimpi paling aneh yang kamu alami?',
    'Kalau kamu boleh memiliki tato, apakah gambar tato tersebut?',
    'Kalau kamu boleh memiliki tato, di bagian tubuh manakah tato tersebut ingin kamu letakkan?',
    'Siapa nama orang pertama yang kamu kenal di perkuliahan?',
    'Siapa nama dosen favoritmu selama masa perkuliahan?',
    'Apa nama film anime yang paling kamu sukai?',
    'Apa mata kuliah favoritmu selama kuliah?',
    'Apa mata kuliah yang paling TIDAK kamu suka selama kuliah?',
    'Tiga kata apa yang mewakili pasangan idamanmu?',
    'Apa acara TV favoritmu?',
    'Teori konspirasi apa yang paling kamu percayai?',
    'Film apa yang pertama kali tonton di bioskop?',
    'Jika kamu disuruh menyanyikan sebuah lagu di karaoke, lagu apakah itu?',
    'Apa film disney kesukaanmu?',
    'Apa hal paling berani yang pernah kamu lakukan?',
    'Apa acara paling seru yang kamu hadiri yang paling berkesan pada masa kecilmu?',
    'Apa hadiah ulang tahunmu yang paling berkesan?',
    'Siapa ilmuwan terkenal yang paling kamu kagumi?',
    'Siapa nama selebriti yang paling kamu kagumi?',
    'Siapa nama atlit olahraga yang paling kamu kagumi?',
    'Siapa pahlawan superhero favoritmu?',
    'Jika kamu mampu memiliki suatu perusahaan top dunia, perusahaan apakah itu?',
    'Apa cemilan yang paling kamu sukai untuk dimakan di malam hari?',
    'Apa nama pokemon yang ingin kamu pelihara?'
]


